// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl1T-pMY8Wz2hI6XWThxG1Uh3MlHlROdU',
    appId: '1:616741473138:web:7e7c621b4cd15c894bebeb',
    messagingSenderId: '616741473138',
    projectId: 'smartcampus-caa98',
    authDomain: 'smartcampus-caa98.firebaseapp.com',
    storageBucket: 'smartcampus-caa98.firebasestorage.app',
    measurementId: 'G-D17ZJ0ZW0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQX--3HgBrvRlX9bF3eMDt_DSZ0olweWc',
    appId: '1:616741473138:android:8ae224ac4e08351b4bebeb',
    messagingSenderId: '616741473138',
    projectId: 'smartcampus-caa98',
    storageBucket: 'smartcampus-caa98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeSNNAcjhcZMJvKlzd57Prmn6CnZrJKH0',
    appId: '1:616741473138:ios:ac7270d39e325ed74bebeb',
    messagingSenderId: '616741473138',
    projectId: 'smartcampus-caa98',
    storageBucket: 'smartcampus-caa98.firebasestorage.app',
    iosBundleId: 'com.alt.smartcampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeSNNAcjhcZMJvKlzd57Prmn6CnZrJKH0',
    appId: '1:616741473138:ios:ac7270d39e325ed74bebeb',
    messagingSenderId: '616741473138',
    projectId: 'smartcampus-caa98',
    storageBucket: 'smartcampus-caa98.firebasestorage.app',
    iosBundleId: 'com.alt.smartcampus',
  );
}
