import 'dart:math';

import 'package:flutter/material.dart';
import 'package:smartcampus/const/color_const.dart';
import 'package:smartcampus/screens/org_dashboard_page.dart';
import 'package:smartcampus/widgets/smc_text.dart';

class RegisterPage extends StatefulWidget {
  final String uuid;

  const RegisterPage({
    super.key,
    required this.uuid,
  });

  @override
  State<RegisterPage> createState() => RegisterPageState();
}

class RegisterPageState extends State<RegisterPage> {
  final GlobalKey<FormState> formKey = GlobalKey<FormState>();
  final TextEditingController orgNameController = TextEditingController();
  final TextEditingController orgAddressController = TextEditingController();
  final TextEditingController orgWebsiteController = TextEditingController();
  final TextEditingController adminNameController = TextEditingController();
  late final TextEditingController adminUuidController;
  String selectedOrgType = 'College';
  late final String autoGeneratedOrgId;

  @override
  void initState() {
    super.initState();
    adminUuidController = TextEditingController(text: widget.uuid);
    autoGeneratedOrgId = generateOrgId();
  }

  @override
  void dispose() {
    orgNameController.dispose();
    orgAddressController.dispose();
    orgWebsiteController.dispose();
    adminNameController.dispose();
    adminUuidController.dispose();
    super.dispose();
  }

  String generateOrgId() {
    final int randomPart = Random().nextInt(9000) + 1000;
    return 'ORG$randomPart';
  }

  void onCreateOrganization() {
    if (!(formKey.currentState?.validate() ?? false)) {
      return;
    }

    Navigator.pushReplacement(
      context,
      MaterialPageRoute(
        builder: (_) => OrgDashboardPage(
          orgId: autoGeneratedOrgId,
          adminName: adminNameController.text.trim(),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: ColorConst.pageBackground,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        title: const smcText(
          textToDisplay: 'Register Organization',
          textSize: 20,
          textBoldness: 4,
          colorOfText: ColorConst.textPrimary,
        ),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16),
          child: Form(
            key: formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const smcText(
                  textToDisplay: 'Create the Organisation',
                  textSize: 17,
                  textBoldness: 3,
                  colorOfText: ColorConst.textPrimary,
                ),
                const SizedBox(height: 10),
                buildField(controller: orgNameController, label: 'Org Name'),
                const SizedBox(height: 10),
                buildOrgTypeDropdown(),
                const SizedBox(height: 10),
                buildField(
                  controller: orgAddressController,
                  label: 'Org Address',
                  maxLines: 2,
                ),
                const SizedBox(height: 10),
                buildField(controller: orgWebsiteController, label: 'Org Website'),
                const SizedBox(height: 10),
                buildField(
                  controller: TextEditingController(text: autoGeneratedOrgId),
                  label: 'Org ID (Auto Generated)',
                  enabled: false,
                ),
                const SizedBox(height: 18),
                const smcText(
                  textToDisplay: 'Assign Org Admin',
                  textSize: 17,
                  textBoldness: 3,
                  colorOfText: ColorConst.textPrimary,
                ),
                const SizedBox(height: 10),
                buildField(
                  controller: adminUuidController,
                  label: 'Admin UUID',
                  enabled: false,
                ),
                const SizedBox(height: 10),
                buildField(controller: adminNameController, label: 'Admin Name'),
                const SizedBox(height: 20),
                SizedBox(
                  width: double.infinity,
                  height: 52,
                  child: ElevatedButton(
                    onPressed: onCreateOrganization,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: ColorConst.primaryBlue,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(14),
                      ),
                    ),
                    child: const smcText(
                      textToDisplay: 'Create Organization',
                      textSize: 15,
                      textBoldness: 3,
                      colorOfText: Colors.white,
                      textAlign: TextAlign.center,
                      maxLines: 1,
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget buildOrgTypeDropdown() {
    const List<String> orgTypes = <String>[
      'College',
      'Company',
      'Research Institute',
      'Training Center',
    ];

    return DropdownButtonFormField<String>(
      initialValue: selectedOrgType,
      decoration: inputDecoration('Org Type'),
      items: orgTypes
          .map(
            (type) => DropdownMenuItem<String>(
              value: type,
              child: smcText(
                textToDisplay: type,
                textSize: 14,
                colorOfText: ColorConst.textPrimary,
              ),
            ),
          )
          .toList(),
      onChanged: (value) {
        if (value != null) {
          setState(() {
            selectedOrgType = value;
          });
        }
      },
    );
  }

  Widget buildField({
    required TextEditingController controller,
    required String label,
    bool enabled = true,
    int maxLines = 1,
  }) {
    return TextFormField(
      controller: controller,
      enabled: enabled,
      maxLines: maxLines,
      style: const TextStyle(color: ColorConst.textPrimary),
      decoration: inputDecoration(label),
      validator: (value) {
        if (!enabled) {
          return null;
        }
        if ((value ?? '').trim().isEmpty) {
          return 'Required';
        }
        return null;
      },
    );
  }

  InputDecoration inputDecoration(String label) {
    return InputDecoration(
      labelText: label,
      filled: true,
      fillColor: Colors.white,
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: const BorderSide(color: ColorConst.borderSoft),
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: const BorderSide(color: ColorConst.borderSoft),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(12),
        borderSide: const BorderSide(color: ColorConst.primaryBlue, width: 1.4),
      ),
    );
  }
}
